### ISSUE TITLE
Is it still possible to use without the Dashboard?

### ISSUE THREAD

**Issue by endel** [britzl/defold-travis-ci#1]
Hi @britzl, thanks a lot for this. I'm trying to set-up unit tests for [colyseus-defold](https://github.com/colyseus/colyseus-defold) using the config you've created here. I wonder if it's still possible to use this approach now that the Defold Dashboard has been deprecated? How can I get my `DEFOLD_AUTH` token? 👀 

Here are the results I've got using this: https://travis-ci.org/colyseus/colyseus-defold/builds/600462271#L198

```
$ ./.travis/run.sh
/home/travis/.travis/functions: line 109: ./.travis/run.sh: Permission denied
The command "./.travis/run.sh" exited with 126.
```

Thanks a lot!

**Comment by britzl** [comment]
Yes, absolutely! I should remove that section. The authentication token was needed when fetching libraries and one or more libraries were hosted on the Defold dashboard. Since the Defold dashboard is shut down the instructions are no longer valid.

The problem you have seems to be that the run.sh command has the wrong permissions. If you're on macOS or Linux it should be enough to `chmod +x .travis/run.sh` and commit.

**Comment by endel** [comment]
Yay, thanks for the clarification @britzl 
I've applied the changes you've made here and it works now! 😊👍
